[package]
name = "advent_of_code_2023"
version = "0.1.0"
authors = ["Pieter Frenssen <pieter@frenssen.be>"]
edition = "2021"

[dependencies]
aoc-runner = "^0.3.0"
aoc-runner-derive = "^0.3.0"
indoc = "^1.0.7"
itertools = "^0.10.5"
regex = "^1.7.0"
